### ISSUE TITLE
More docs

### ISSUE THREAD

**Issue by xfq** [kenchris/sensor-polyfills#1]
Document which interfaces this polyfill implements would be useful. A live sample web app using this polyfill is great too. And document the supported browser versions, how to use it with or without npm etc.

**Comment by anssiko** [comment]
@xfq thanks for your suggestions! A partial fix #2 landed.

Let us know if have further ideas for improvements.

**Comment by anssiko** [comment]
We now have a better demo using the polyfill, linked to from the readme also:

https://intel.github.io/generic-sensor-demos/orientation-phone/

Tested with Safari on iOS 11.2 (iPhone 8), Chrome 62+ on Android 8.0.0 (Pixel XL) with both the native Generic Sensors implementation disabled and enabled (in the latter case, the native implementation is used naturally).

**Comment by anssiko** [comment]
@xfq, if you have more devices to test with, please test and provide us feedback!

**Comment by kenchris** [comment]
Is this good enough now?

**Comment by xfq** [comment]
Thanks to Anssi, it's a lot better now. The only thing missing, in my opinion, is the supported browser versions of the polyfill.

**Comment by xfq** [comment]
It would be good to document `geolocation-sensor.js` too. I see only motion sensors mentioned in `README.md` currently.

**Comment by anssiko** [comment]
@xfq, good catch, thanks! Now added to the README.md.
