### ISSUE TITLE
Implement GravitySensor

### ISSUE THREAD

**Issue by reillyeon** [kenchris/sensor-polyfills#16]
An implementation of this sensor is being prototyped in Chromium.

**Comment by kenchris** [comment]
This is already implemented here https://github.com/kenchris/sensor-polyfills/blob/master/src/motion-sensors.js#L402

DeviceMotion exposes "Acceleration" (acceleration with gravity) and "Linear Acceleration" (acceleration without gravity) - so it is easy to isolate gravity from that.

I don't know if there are any systems only supporting one of the values, but it is also possible to derive linear acceleration and gravity from acceleration with a low and high pass filter:

http://josejuansanchez.org/android-sensors-overview/gravity_and_linear_acceleration/README.html

**Comment by reillyeon** [comment]
Thanks. Somehow I missed this before filing this issue.
