### ISSUE TITLE
Reference frame option for Accelerometer and Gyroscope

### ISSUE THREAD

**Issue by anssiko** [kenchris/sensor-polyfills#9]
To sync with the latest spec changes, the polyfill would need to implement:

https://w3c.github.io/accelerometer/#dom-accelerometersensoroptions-referenceframe
https://w3c.github.io/gyroscope/#dom-gyroscopesensoroptions-referenceframe

This would complement https://github.com/kenchris/sensor-polyfills/commit/549c78edadac07d15a39fd689e896062fba54a51 that patched `RelativeOrientationSensor` and `AbsoluteOrientationSensor`.

Cc @pozdnyakov

**Comment by kenchris** [comment]
fixed
